//
//  main.cpp
//  PAT-1035-Password
//
//  Created by 程锋 on 15/8/25.
//  Copyright (c) 2015年 程锋. All rights reserved.
/**
 *  To prepare for PAT, the judge sometimes has to generate random passwords for the users. The problem is that there are always some confusing passwords since it is hard to distinguish 1 (one) from l (L in lowercase), or 0 (zero) from O (o in uppercase). One solution is to replace 1 (one) by @, 0 (zero) by %, l by L, and O by o. Now it is your job to write a program to check the accounts generated by the judge, and to help the juge modify the confusing passwords.
 
     Input Specification:
     
     Each input file contains one test case. Each case contains a positive integer N (<= 1000), followed by N lines of accounts. Each account consists of a user name and a password, both are strings of no more than 10 characters with no space.
     
     Output Specification:
     
     For each test case, first print the number M of accounts that have been modified, then print in the following M lines the modified accounts info, that is, the user names and the corresponding modified passwords. The accounts must be printed in the same order as they are read in. If no account is modified, print in one line "There are N accounts and no account is modified" where N is the total number of accounts. However, if N is one, you must print "There is 1 account and no account is modified" instead.
     
     Sample Input 1:
     
     3
     Team000002 Rlsp0dfa
     Team000003 perfectpwd
     Team000001 R1spOdfa
     Sample Output 1:
     2
     Team000002 RLsp%dfa
     Team000001 R@spodfa
     Sample Input 2:
     1
     team110 abcdefg332
     Sample Output 2:
     There is 1 account and no account is modified
     Sample Input 3:
     2
     team110 abcdefg222
     team220 abcdefg333
     Sample Output 3:
     There are 2 accounts and no account is modified
 */

#include <iostream>
#include <string.h>

using namespace std;

struct Account{
    char id[11];
    char pwd[11];
}acc[1001];

bool mark[1001];

int main(int argc, const char * argv[]) {
    
    freopen("/Users/chengfeng/Dev/Algorithm/PAT甲级/PAT-1035-Password/PAT-1035-Password/in", "r", stdin);

    int n;
    
    while(cin >> n && n != 0)
    {
        
        for(int i = 1; i <= n; ++i)
        {
            mark[i] = false;
            
            char id[11];
            char pwd[11];
            
            cin >> id >> pwd;
            strcpy(acc[i].id, id);
            strcpy(acc[i].pwd, pwd);
        }
        
        for(int i = 1; i <= n; ++i)
        {
            for(int j = 0; j < (int)strlen(acc[i].pwd); ++j)
            {
                if(acc[i].pwd[j] == '1')
                {
                    acc[i].pwd[j] = '@';
                    mark[i] = true;
                }
                if(acc[i].pwd[j] == 'l')
                {
                    acc[i].pwd[j] = 'L';
                    mark[i] = true;
                }
                if(acc[i].pwd[j] == '0')
                {
                    acc[i].pwd[j] = '%';
                    mark[i] = true;
                }
                if(acc[i].pwd[j] == 'O')
                {
                    acc[i].pwd[j] = 'o';
                    mark[i] = true;
                }
            }
        }
        
        int cnt = 0;
        for(int i = 1; i <= n; ++i)
            if(mark[i])
                cnt++;
        
        if(cnt == 0)
        {
            if(n > 1)
            {
                cout << "There are " << n << " accounts and no account is modified" << endl;
                return 0;
            }
            
            cout << "There is " << n << " account and no account is modified" << endl;
            return 0;
        }
        
        cout << cnt << endl;
        
        for(int i = 1; i <= n; ++i)
            if(mark[i])
                cout << acc[i].id << " " << acc[i].pwd << endl;
        
        
    }
    
    return 0;
}













